"""Telegram notification and i18n helpers for InteractiveBrokersPlatform."""

from __future__ import annotations


I18N = {
    "zh": {
        "rebalance_title": "🔔 【调仓指令】",
        "heartbeat_title": "💓 【心跳检测】",
        "error_title": "🚨 【策略异常】",
        "health_probe_title": "🔎 【连接探针】",
        "health_probe_error_prefix": "健康探针异常:\n",
        "canary_title": "🐤 【金丝雀检查】",
        "strategy_label": "🧭 策略: {name}",
        "account_ids_detail": "🆔 账户: {account_ids}",
        "market_scope_detail": "🌏 市场: {market} | 交易币种: {currency} | 交易所: {exchange} | 日历: {calendar}",
        "equity": "净值",
        "buying_power": "购买力",
        "reserved_cash": "预留现金",
        "investable_cash": "可投资现金",
        "cash_label": "现金",
        "empty_positions": "  (空仓)",
        "empty_target_weights": "  (无目标持仓)",
        "account_summary_title": "📊 账户摘要",
        "positions_title": "💼 当前持仓",
        "execution_summary_title": "🧾 执行摘要",
        "target_weights_title": "目标持仓",
        "strategy_profile_detail": "策略={profile}",
        "execution_profile_detail": "执行配置={profile}",
        "regime_detail": "市场阶段={value}",
        "breadth_detail": "宽度={value}",
        "target_stock_detail": "目标股票仓位={value}",
        "realized_stock_detail": "实际股票仓位={value}",
        "safe_haven_target_detail": "目标避险仓位={value}",
        "snapshot_decision_detail": "快照决策={value}",
        "snapshot_as_of_detail": "快照日期={value}",
        "snapshot_age_days_detail": "快照账龄={value}",
        "snapshot_file_ts_detail": "快照文件时间={value}",
        "snapshot_path_detail": "快照路径={value}",
        "config_source_detail": "配置来源={value}",
        "dry_run_snapshot_prices": "🧪 模拟运行估价: 使用快照收盘价 {count}个标的 ({symbols})",
        "price_fallback_prices": "📌 执行估价: 使用最近收盘价 {count}个标的 ({symbols})",
        "target_diff_summary": "调仓变化: {details}",
        "no_order_plan_reason": "未下单: {reason}",
        "buy_deferred": "ℹ️ [买入说明] {detail}",
        "buy_deferred_small_account_cash_substitution": "{symbol} 目标金额 ${diff} 低于 1 股价格 ${price}；为避免超过目标仓位，小账户本轮保留现金，不回补 {cash_symbols}",
        "trade_date_detail": "交易日={value}",
        "target_diff": "目标差异 {symbol}: 当前={current} 目标={target} 变化={delta}",
        "pending_orders_detected": "检测到未完成订单: 策略={profile} 标的={symbols}",
        "same_day_fills_detected": "检测到当日成交: 策略={profile} 模式={mode} 标的={symbols} 交易日={trade_date}",
        "same_day_execution_locked": "当日执行锁已存在: 策略={profile} 模式={mode} 交易日={trade_date} 快照日期={snapshot_date} 目标哈希={target_hash} 锁文件={lock_path}",
        "execution_lock_acquired": "已获取执行锁: 模式={mode} 交易日={trade_date} 快照日期={snapshot_date} 锁文件={lock_path}",
        "same_day_execution_locked_notice": "当日已执行过: 模式={mode} | 交易日={trade_date} | 快照日期={snapshot_date}",
        "dry_run_buy_batch": "🧪 模拟买入 {count}个标的: {details}",
        "dry_run_sell_batch": "🧪 模拟卖出 {count}个标的: {details}",
        "submitted_buy_batch": "📈 已提交买单 {count}个标的: {details}",
        "submitted_sell_batch": "📉 已提交卖单 {count}个标的: {details}",
        "filled_buy_batch": "✅ 买单成交 {count}个标的: {details}",
        "filled_sell_batch": "✅ 卖单成交 {count}个标的: {details}",
        "partial_buy_batch": "⚠️ 买单部分成交 {count}个标的: {details}",
        "partial_sell_batch": "⚠️ 卖单部分成交 {count}个标的: {details}",
        "no_equity": "❌ 无净值",
        "signal_label": "信号",
        "signal_monthly_snapshot_waiting": "月度快照节奏 | 等待进入执行窗口",
        "status_monthly_snapshot_waiting_window": "不执行 | 原因=当前不在月度执行窗口 | 快照日期={snapshot_as_of} | 允许日期={allowed_dates}",
        "status_no_execution_window_after_snapshot": "不执行 | 原因=快照后没有可用执行窗口 | 快照日期={snapshot_as_of}",
        "snapshot_guard_decision_proceed": "继续",
        "snapshot_guard_decision_no_op": "不执行",
        "snapshot_guard_decision_fail_closed": "关闭执行",
        "market_status_risk_on": "🚀 风险开启（{asset}）",
        "market_status_delever": "🛡️ 降杠杆（{asset}）",
        "signal_risk_on": "SOXL 站上 {window} 日均线，持有 SOXL，交易层风险仓位 {ratio}",
        "signal_delever": "SOXL 跌破 {window} 日均线，切换至 SOXX，交易层风险仓位 {ratio}",
        "market_status_blend_gate_risk_on": "🚀 风险开启（{asset}）",
        "market_status_blend_gate_defensive": "🛡️ 降杠杆（{asset}）",
        "signal_blend_gate_risk_on": "{trend_symbol} 站上 {window} 日门槛线，持有 SOXL {soxl_ratio} + SOXX {soxx_ratio}",
        "signal_blend_gate_defensive": "{trend_symbol} 跌破门槛线，防守持有 SOXX {soxx_ratio}",
        "market_status_blend_gate_overlay_capped": "🧯 风控降档（{asset}）",
        "signal_blend_gate_overlay_capped": "{trend_symbol} 仍在 {window} 日门槛线上方，但触发风控降档（{reasons}），目标仓位 {allocation_text}",
        "blend_gate_reason_rsi_cap": "RSI 超阈值",
        "blend_gate_reason_bollinger_cap": "突破布林上轨",
        "blend_gate_reason_volatility_delever": "{symbol} {window} 日年化波动率 {volatility} 高于 {threshold}，SOXL 转向 {redirect_symbol}",
        "strategy_plugin_line": "🧩 插件：{plugin} | 状态：{route} | 提醒：{action}",
        "strategy_plugin_alert_subject": "🚨 策略插件告警：{plugin} | {route}",
        "strategy_plugin_alert_title": "🚨 【策略插件告警】",
        "strategy_plugin_alert_context": "运行环境：{context}",
        "strategy_plugin_alert_strategy": "策略：{strategy}",
        "strategy_plugin_alert_plugin": "插件：{plugin}",
        "strategy_plugin_alert_status": "状态：{route}",
        "strategy_plugin_alert_action": "人工处理建议：{action}",
        "strategy_plugin_alert_mode": "模式：{mode}",
        "strategy_plugin_alert_as_of": "信号时间：{as_of}",
        "strategy_plugin_alert_guidance": "处置建议：{guidance}",
        "strategy_plugin_alert_scope_note": "执行范围：{scope_note}",
        "strategy_plugin_alert_scope": "仅作人工复核提醒；插件不会自动下单或改仓位",
        "strategy_plugin_name_crisis_response_shadow": "危机观察通知",
        "strategy_plugin_name_taco_rebound_shadow": "TACO 抄底观察通知",
        "strategy_plugin_mode_shadow": "影子观察",
        "strategy_plugin_route_no_action": "未触发",
        "strategy_plugin_route_true_crisis": "真危机",
        "strategy_plugin_route_taco_rebound": "TACO 反弹确认",
        "strategy_plugin_route_unknown_route": "未知状态",
        "strategy_plugin_action_no_action": "不操作",
        "strategy_plugin_action_watch_only": "仅通知",
        "strategy_plugin_action_notify_manual_review": "通知人工复核",
        "strategy_plugin_action_defend": "防守",
        "strategy_plugin_action_blocked": "已阻断",
        "strategy_plugin_action_monitor": "持续观察",
        "strategy_plugin_action_unknown_action": "未知提醒",
        "strategy_plugin_guidance_crisis_response_shadow_true_crisis_defend": "优先考虑降低杠杆或清理杠杆仓位，暂停加仓；如需保留风险敞口，先降到可承受的小仓位。",
        "strategy_plugin_guidance_crisis_response_shadow_no_action_blocked": "危机路线被风控阻断；先核对数据新鲜度和外部情境，不建议仅凭此条加仓。",
        "strategy_plugin_guidance_taco_rebound_shadow_taco_rebound_notify_manual_review": "TACO 仅提示可能的反弹窗口；可考虑小仓位、分批、预设止损/失效条件的人工博弈，不建议一次性满仓。",
        "no_trades": "✅ 无需调仓",
        "emergency": "🛡️ 金丝雀应急: {n_bad}/4 坏, 全部转入 {safe}",
        "quarterly": "📊 季度调仓: 前 {n} 名轮动",
        "daily_check": "📋 每日检查: 金丝雀正常, 持仓不变",
        "hold": "💎 持仓不变",
        "market_sell": "📉 [市价卖出] {symbol}: {qty}股",
        "limit_buy": "📈 [限价买入] {symbol}: {qty}股 @ ${price}",
        "submitted": "已下发（订单号: {order_id}）",
        "failed": "失败: {reason}",
        "order_filled": "✅ 订单成交 | {symbol} {side} {qty}股 均价 ${price}（订单号: {order_id}）",
        "order_partial": "⚠️ 部分成交 | {symbol} {side} {executed}/{qty}股 均价 ${price}（订单号: {order_id}）",
        "order_rejected": "❌ 订单异常 | {symbol} {side} {qty}股 状态: {status}（订单号: {order_id}）",
        "paper_liquidation_only": "IBKR 模拟账户清仓模式",
        "paper_liquidation_status": "模式={mode} 状态={status}",
        "paper_liquidation_positions_seen": "识别持仓={count}",
        "signal_state_hold": "趋势持有",
        "signal_state_entry": "入场信号",
        "signal_state_reduce": "减仓信号",
        "signal_state_exit": "离场信号",
        "signal_state_idle": "等待信号",
        "small_account_warning_note": "小账户提示：净值 {portfolio_equity} 低于建议 {min_recommended_equity}；{reason}",
        "small_account_warning_reason_integer_shares_min_position_value_may_prevent_backtest_replication": "整数股和最小仓位限制可能导致实盘无法完全复现回测",
        "strategy_name_global_etf_rotation": "全球 ETF 轮动",
        "strategy_name_global_etf_confidence_vol_gate": "全球 ETF 置信波动门控",
        "strategy_name_russell_1000_multi_factor_defensive": "罗素1000多因子",
        "strategy_name_tech_communication_pullback_enhancement": "科技通信回调增强",
        "strategy_name_qqq_tech_enhancement": "科技通信回调增强",
        "strategy_name_mega_cap_leader_rotation_top50_balanced": "Mega Cap Top50 平衡龙头轮动",
        "strategy_name_nasdaq_sp500_smart_dca": "纳斯达克 / 标普智能定投",
        "strategy_name_hk_global_etf_tactical_rotation": "港股全球 ETF 战术轮动",
        "strategy_name_hk_dividend_gold_defensive_rotation": "港股股息黄金防守轮动",
        "strategy_name_hk_low_vol_dividend_quality_snapshot": "港股低波股息质量快照",
        "strategy_name_tqqq_growth_income": "TQQQ 增长收益",
        "strategy_name_soxl_soxx_trend_income": "SOXL/SOXX 半导体趋势收益",
    },
    "en": {
        "rebalance_title": "🔔 【Trade Execution Report】",
        "heartbeat_title": "💓 【Heartbeat】",
        "error_title": "🚨 【Strategy Error】",
        "health_probe_title": "🔎 【Health Probe】",
        "health_probe_error_prefix": "Health probe error:\n",
        "canary_title": "🐤 【Canary Check】",
        "strategy_label": "🧭 Strategy: {name}",
        "account_ids_detail": "🆔 Account: {account_ids}",
        "market_scope_detail": "🌏 Market: {market} | trading currency: {currency} | exchange: {exchange} | calendar: {calendar}",
        "equity": "Equity",
        "buying_power": "Buying Power",
        "reserved_cash": "Reserved Cash",
        "investable_cash": "Investable Cash",
        "cash_label": "Cash",
        "empty_positions": "  (No positions)",
        "empty_target_weights": "  (No target positions)",
        "account_summary_title": "📊 Account Summary",
        "positions_title": "💼 Current Positions",
        "execution_summary_title": "🧾 Execution Summary",
        "target_weights_title": "Target Weights",
        "strategy_profile_detail": "strategy_profile={profile}",
        "execution_profile_detail": "profile={profile}",
        "regime_detail": "regime={value}",
        "breadth_detail": "breadth={value}",
        "target_stock_detail": "target_stock={value}",
        "realized_stock_detail": "realized_stock={value}",
        "safe_haven_target_detail": "safe_haven_target={value}",
        "snapshot_decision_detail": "snapshot_decision={value}",
        "snapshot_as_of_detail": "snapshot_as_of={value}",
        "snapshot_age_days_detail": "snapshot_age_days={value}",
        "snapshot_file_ts_detail": "snapshot_file_ts={value}",
        "snapshot_path_detail": "snapshot_path={value}",
        "config_source_detail": "config_source={value}",
        "dry_run_snapshot_prices": "🧪 dry-run pricing: snapshot close for {count} symbols ({symbols})",
        "price_fallback_prices": "📌 execution pricing: recent close for {count} symbols ({symbols})",
        "target_diff_summary": "Target changes: {details}",
        "no_order_plan_reason": "No order submitted: {reason}",
        "buy_deferred": "ℹ️ [Buy note] {detail}",
        "buy_deferred_small_account_cash_substitution": "{symbol} target ${diff} is below the 1-share price ${price}; to avoid exceeding the target allocation, this small account keeps cash this cycle and does not rebuy {cash_symbols}",
        "trade_date_detail": "trade_date={value}",
        "target_diff": "target_diff {symbol}: current={current} target={target} delta={delta}",
        "pending_orders_detected": "pending_orders_detected profile={profile} symbols={symbols}",
        "same_day_fills_detected": "same_day_fills_detected profile={profile} mode={mode} symbols={symbols} trade_date={trade_date}",
        "same_day_execution_locked": "same_day_execution_locked profile={profile} mode={mode} trade_date={trade_date} snapshot_date={snapshot_date} target_hash={target_hash} lock_path={lock_path}",
        "execution_lock_acquired": "execution_lock_acquired mode={mode} trade_date={trade_date} snapshot_date={snapshot_date} lock_path={lock_path}",
        "same_day_execution_locked_notice": "same-day execution already exists: mode={mode} trade_date={trade_date} snapshot_date={snapshot_date}",
        "dry_run_buy_batch": "🧪 dry-run buys for {count} symbols: {details}",
        "dry_run_sell_batch": "🧪 dry-run sells for {count} symbols: {details}",
        "submitted_buy_batch": "📈 Submitted buy orders for {count} symbols: {details}",
        "submitted_sell_batch": "📉 Submitted sell orders for {count} symbols: {details}",
        "filled_buy_batch": "✅ Filled buy orders for {count} symbols: {details}",
        "filled_sell_batch": "✅ Filled sell orders for {count} symbols: {details}",
        "partial_buy_batch": "⚠️ Partial buy fills for {count} symbols: {details}",
        "partial_sell_batch": "⚠️ Partial sell fills for {count} symbols: {details}",
        "no_equity": "❌ No equity",
        "signal_label": "Signal",
        "signal_monthly_snapshot_waiting": "monthly snapshot cadence | waiting inside execution window",
        "status_monthly_snapshot_waiting_window": "no-op | reason=outside monthly execution window | snapshot_as_of={snapshot_as_of} | allowed={allowed_dates}",
        "status_no_execution_window_after_snapshot": "no-op | reason=no execution window after snapshot | snapshot_as_of={snapshot_as_of}",
        "snapshot_guard_decision_proceed": "proceed",
        "snapshot_guard_decision_no_op": "no_op",
        "snapshot_guard_decision_fail_closed": "fail_closed",
        "market_status_risk_on": "🚀 RISK-ON ({asset})",
        "market_status_delever": "🛡️ DE-LEVER ({asset})",
        "signal_risk_on": "SOXL above {window}d MA, hold SOXL, risk {ratio}",
        "signal_delever": "SOXL below {window}d MA, switch to SOXX, risk {ratio}",
        "market_status_blend_gate_risk_on": "🚀 RISK-ON ({asset})",
        "market_status_blend_gate_defensive": "🛡️ DE-LEVER ({asset})",
        "signal_blend_gate_risk_on": "{trend_symbol} above {window}d gated entry, hold SOXL {soxl_ratio} + SOXX {soxx_ratio}",
        "signal_blend_gate_defensive": "{trend_symbol} below gated entry, hold defensive SOXX {soxx_ratio}",
        "market_status_blend_gate_overlay_capped": "🧯 RISK-CAP ({asset})",
        "signal_blend_gate_overlay_capped": "{trend_symbol} stays above the {window}d gate, but risk cap ({reasons}) cuts exposure to {allocation_text}",
        "blend_gate_reason_rsi_cap": "RSI over threshold",
        "blend_gate_reason_bollinger_cap": "price above upper band",
        "blend_gate_reason_volatility_delever": "{symbol} {window}d annualized volatility {volatility} is above {threshold}; redirect SOXL to {redirect_symbol}",
        "strategy_plugin_line": "🧩 Plugin: {plugin} | status: {route} | notice: {action}",
        "strategy_plugin_alert_subject": "🚨 Strategy plugin alert: {plugin} | {route}",
        "strategy_plugin_alert_title": "🚨 【Strategy Plugin Alert】",
        "strategy_plugin_alert_context": "Context: {context}",
        "strategy_plugin_alert_strategy": "Strategy: {strategy}",
        "strategy_plugin_alert_plugin": "Plugin: {plugin}",
        "strategy_plugin_alert_status": "Status: {route}",
        "strategy_plugin_alert_action": "Notice: {action}",
        "strategy_plugin_alert_mode": "Mode: {mode}",
        "strategy_plugin_alert_as_of": "Signal as-of: {as_of}",
        "strategy_plugin_alert_guidance": "Manual guidance: {guidance}",
        "strategy_plugin_alert_scope_note": "Execution scope: {scope_note}",
        "strategy_plugin_alert_scope": "Manual review notice only; the plugin does not place orders or change allocations",
        "strategy_plugin_name_crisis_response_shadow": "Crisis Watch Notice",
        "strategy_plugin_name_taco_rebound_shadow": "TACO Rebound Watch Notice",
        "strategy_plugin_mode_shadow": "shadow",
        "strategy_plugin_route_no_action": "no alert",
        "strategy_plugin_route_true_crisis": "true crisis",
        "strategy_plugin_route_taco_rebound": "TACO rebound confirmed",
        "strategy_plugin_route_unknown_route": "unknown status",
        "strategy_plugin_action_no_action": "no action",
        "strategy_plugin_action_watch_only": "notify only",
        "strategy_plugin_action_notify_manual_review": "notify manual review",
        "strategy_plugin_action_defend": "defend",
        "strategy_plugin_action_blocked": "blocked",
        "strategy_plugin_action_monitor": "watch",
        "strategy_plugin_action_unknown_action": "unknown notice",
        "strategy_plugin_guidance_crisis_response_shadow_true_crisis_defend": "Consider reducing or clearing leveraged exposure, then pause new risk additions; if keeping exposure, resize it to a small amount you can tolerate.",
        "strategy_plugin_guidance_crisis_response_shadow_no_action_blocked": "A guard blocked the crisis route; verify data freshness and external context before acting on this alert.",
        "strategy_plugin_guidance_taco_rebound_shadow_taco_rebound_notify_manual_review": "TACO only flags a possible rebound window; consider a small staged manual probe with a predefined invalidation level instead of full-size exposure.",
        "no_trades": "✅ No rebalance needed",
        "emergency": "🛡️ Canary Emergency: {n_bad}/4 bad, rotating to {safe}",
        "quarterly": "📊 Quarterly Rebalance: Top {n} rotation",
        "daily_check": "📋 Daily Check: canary OK, holding",
        "hold": "💎 Hold positions",
        "market_sell": "📉 [Market sell] {symbol}: {qty} shares",
        "limit_buy": "📈 [Limit buy] {symbol}: {qty} shares @ ${price}",
        "submitted": "submitted (ID: {order_id})",
        "failed": "failed: {reason}",
        "order_filled": "✅ Filled | {symbol} {side} {qty} shares avg ${price} (ID: {order_id})",
        "order_partial": "⚠️ Partial | {symbol} {side} {executed}/{qty} shares avg ${price} (ID: {order_id})",
        "order_rejected": "❌ Rejected | {symbol} {side} {qty} shares status: {status} (ID: {order_id})",
        "paper_liquidation_only": "IBKR paper liquidation only",
        "paper_liquidation_status": "mode={mode} status={status}",
        "paper_liquidation_positions_seen": "positions_seen={count}",
        "signal_state_hold": "Trend Hold",
        "signal_state_entry": "Entry Signal",
        "signal_state_reduce": "Reduce Signal",
        "signal_state_exit": "Exit Signal",
        "signal_state_idle": "Idle",
        "small_account_warning_note": "small account warning: portfolio equity {portfolio_equity} is below recommended {min_recommended_equity}; {reason}",
        "small_account_warning_reason_integer_shares_min_position_value_may_prevent_backtest_replication": "integer-share minimum position sizing may prevent backtest replication",
        "strategy_name_global_etf_rotation": "Global ETF Rotation",
        "strategy_name_global_etf_confidence_vol_gate": "Global ETF Confidence Vol Gate",
        "strategy_name_russell_1000_multi_factor_defensive": "Russell 1000 Multi-Factor",
        "strategy_name_tech_communication_pullback_enhancement": "Tech/Communication Pullback Enhancement",
        "strategy_name_qqq_tech_enhancement": "Tech/Communication Pullback Enhancement",
        "strategy_name_mega_cap_leader_rotation_top50_balanced": "Mega Cap Leader Rotation Top50 Balanced",
        "strategy_name_nasdaq_sp500_smart_dca": "Nasdaq/S&P 500 Smart DCA",
        "strategy_name_hk_global_etf_tactical_rotation": "HK Global ETF Tactical Rotation",
        "strategy_name_hk_dividend_gold_defensive_rotation": "HK Dividend-Gold Defensive Rotation",
        "strategy_name_hk_low_vol_dividend_quality_snapshot": "HK Low-Vol Dividend Quality Snapshot",
        "strategy_name_tqqq_growth_income": "TQQQ Growth Income",
        "strategy_name_soxl_soxx_trend_income": "SOXL/SOXX Semiconductor Trend Income",
    },
}


def build_translator(lang):
    def translate(key, **kwargs):
        active_lang = lang if lang in I18N else "en"
        template = I18N[active_lang].get(key, key)
        return template.format(**kwargs) if kwargs else template

    return translate


def build_strategy_display_name(translate_fn):
    def strategy_display_name(profile: str, *, fallback_name: str | None = None) -> str:
        key = f"strategy_name_{str(profile or '').strip()}"
        translated = translate_fn(key)
        if translated != key:
            return translated
        fallback = str(fallback_name or "").strip()
        if fallback:
            return fallback
        return str(profile or "").strip()

    return strategy_display_name


def send_telegram_message(
    message,
    *,
    token,
    chat_id,
    requests_module,
    printer=print,
):
    if not token or not chat_id:
        return

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    try:
        printer(f"TG:\n{message}", flush=True)
        response = requests_module.post(
            url,
            json={"chat_id": chat_id, "text": message},
            timeout=10,
        )
        if not 200 <= response.status_code < 300:
            printer(
                f"Telegram send failed with status {response.status_code}: {response.text}",
                flush=True,
            )
    except Exception as exc:
        printer(f"Telegram send failed: {exc}", flush=True)
